import { env } from "cloudflare:test";
import { generateApiKey, type KeyMode } from "../src/lib/keys";
import type { ScopeOp } from "../src/auth/scopes";

export const NOW = 1_780_000_000_000;

export const WORKSPACE_A = "ws_AAAAAAAAAAAAAAAAAAAAAAAAAA";
export const WORKSPACE_B = "ws_BBBBBBBBBBBBBBBBBBBBBBBBBB";
const USER_ID = "usr_TESTUSER";
const ORG_ID = "org_TESTORG";

/**
 * Seed two workspaces under one org, so cross-tenant access has something real
 * to attempt. Idempotent: safe to call from every test.
 */
export async function seedTwoWorkspaces(): Promise<void> {
  await env.DB.prepare(
    `INSERT OR IGNORE INTO users (id, email, created_at, updated_at) VALUES (?, ?, ?, ?)`
  ).bind(USER_ID, "test@example.com", NOW, NOW).run();

  await env.DB.prepare(
    `INSERT OR IGNORE INTO organizations (id, name, owner_user_id, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?)`
  ).bind(ORG_ID, "Test Org", USER_ID, NOW, NOW).run();

  for (const [id, name] of [[WORKSPACE_A, "Workspace A"], [WORKSPACE_B, "Workspace B"]] as const) {
    await env.DB.prepare(
      `INSERT OR IGNORE INTO workspaces (id, org_id, name, period_reset_at, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?)`
    ).bind(id, ORG_ID, name, NOW, NOW, NOW).run();
  }
}

/** Remove all workspace-owned rows between tests. */
export async function resetTenantData(): Promise<void> {
  for (const table of ["file_tags", "files", "folders", "api_keys", "agents", "audit_events"]) {
    await env.DB.prepare(`DELETE FROM ${table}`).run();
  }
}

/**
 * Mint a real key: generated by the production code path, hashed the same way,
 * inserted as a real row. A test that hand-writes a hash proves the test's idea
 * of the format, not the implementation's.
 */
export async function seedApiKey(options: {
  workspaceId?: string;
  agentId?: string | null;
  mode?: KeyMode;
  ops?: ScopeOp[];
  pathPrefix?: string;
  expiresAt?: number | null;
  revokedAt?: number | null;
  now?: number;
}): Promise<{ token: string; keyId: string }> {
  const {
    workspaceId = WORKSPACE_A,
    agentId = null,
    mode = "live",
    ops = ["read", "write", "delete", "list"],
    pathPrefix = "/*",
    expiresAt = null,
    revokedAt = null,
    now = NOW,
  } = options;

  const generated = await generateApiKey(mode);
  const keyId = `key_${crypto.randomUUID().replace(/-/g, "").slice(0, 26).toUpperCase()}`;

  await env.DB.prepare(
    `INSERT INTO api_keys
       (id, workspace_id, agent_id, name, key_prefix, key_last_four, key_hash,
        scopes, created_by_user_id, parent_key_id, expires_at, last_used_at,
        revoked_at, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, ?, NULL, ?, ?)`
  )
    .bind(
      keyId,
      workspaceId,
      agentId,
      "test key",
      generated.keyPrefix,
      generated.keyLastFour,
      generated.keyHash,
      JSON.stringify({ ops, pathPrefix }),
      USER_ID,
      expiresAt,
      revokedAt,
      now
    )
    .run();

  return { token: generated.token, keyId };
}

export async function seedAgent(options: {
  id: string;
  workspaceId?: string;
  status?: "active" | "disabled";
}): Promise<string> {
  const { id, workspaceId = WORKSPACE_A, status = "active" } = options;
  await env.DB.prepare(
    `INSERT OR REPLACE INTO agents
       (id, workspace_id, name, status, created_by_user_id, created_at)
     VALUES (?, ?, ?, ?, ?, ?)`
  )
    .bind(id, workspaceId, `agent-${id}`, status, USER_ID, NOW)
    .run();
  return id;
}

/** Restore a workspace to `active` after a test suspends it. */
export async function setWorkspaceStatus(workspaceId: string, status: string): Promise<void> {
  await env.DB.prepare(`UPDATE workspaces SET status = ? WHERE id = ?`)
    .bind(status, workspaceId)
    .run();
}

export function bearer(token: string): HeadersInit {
  return { authorization: `Bearer ${token}` };
}

/** Clear the KV namespace the rate limiter counts in, between tests. */
export async function resetRateLimits(): Promise<void> {
  const { keys } = await env.CACHE.list({ prefix: "rl:" });
  for (const key of keys) {
    await env.CACHE.delete(key.name);
  }
}

/** Remove everything the bootstrap flow creates, including its provisional rows. */
export async function resetBootstrapData(): Promise<void> {
  await env.DB.prepare(`DELETE FROM api_keys`).run();
  await env.DB.prepare(`DELETE FROM agents`).run();
  await env.DB.prepare(`DELETE FROM workspaces WHERE claimed_at IS NULL`).run();
  await env.DB.prepare(`DELETE FROM organizations WHERE id NOT IN (SELECT org_id FROM workspaces)`).run();
  await env.DB.prepare(`DELETE FROM users WHERE is_provisional = 1`).run();
}
